### ISSUE TITLE
Redaction des questions et réponses

### ISSUE THREAD

**Issue by Maxime-p** [MaximeCours/rendu-web3-team1#6]
VERSION CODE SOLIDITY EN COMMENTAIRES

* Qu'est-ce que le Web 3.0 ?
    * A. Une version améliorée du navigateur Internet Explorer.
    * B. Un réseau social populaire.
    * C. Un nouveau protocole de communication pour le courrier électronique.
    * **D. Une évolution du Web vers un Internet décentralisé.**
    
* Quel est le principal objectif du Web 3.0 ?
    * A. Améliorer la vitesse de connexion Internet.
    * **B. Décentraliser les applications et les données.**
    * C. Augmenter la résolution des écrans d'ordinateur.
    * D. Réduire la taille des fichiers multimédias.

* Qu'est-ce qu'un smart contract ?
    * A. Un contrat intelligent entre deux entreprises.
    * B. Un document juridique traditionnel.
    * C. Un accord verbal entre parties contractantes.
    * **D. Un programme informatique auto-exécutable sur une blockchain.**
    
* Quelle blockchain est principalement associée à l'utilisation de smart contracts ?
    * A. Bitcoin.
    * **B. Ethereum.**
    * C. Ripple.
    * D. Litecoin.

* Comment fonctionne la décentralisation dans le contexte du Web 3.0 ?
    * **A. Les données sont réparties sur plusieurs nœuds sans contrôle central.**
    * B. Toutes les données sont stockées sur un seul serveur.
    * C. Un seul utilisateur a le contrôle total du réseau.
    * D. Les données sont stockées uniquement sur des serveurs gouvernementaux.

* Quelle est la caractéristique principale d'un smart contract par rapport à un contrat traditionnel ?
    * A. Il nécessite une signature manuscrite.
    * **B. Il est exécuté automatiquement sans intermédiaire.**
    * C. Il peut être annulé à tout moment.
    * D. Il est stocké sur une base de données centralisée.

* Quel langage de programmation est souvent utilisé pour écrire des smart contracts ?
    * A. Python.
    * B. JavaScript.
    * **C. Solidity.**
    * D. Ruby.

* Qu'est-ce que Hardhat dans le contexte du développement de smart contracts ?
    * **A. Un environnement de développement pour Ethereum.**
    * B. Une casquette résistante.
    * C. Un protocole de sécurité sur Internet.
    * D. Un langage de programmation.
    
* Quel est le rôle principal de MetaMask dans l'écosystème Ethereum ?
    * A. Gérer les mots de passe des utilisateurs.
    * B. Faciliter l'échange de cryptomonnaies.
    * **C. Fournir une interface utilisateur pour les smart contracts.**
    * D. Stocker des fichiers sur la blockchain.

* Qu'est-ce que Sepolia dans le contexte du Web 3.0 ?
    * **A. Un réseau social décentralisé.**
    * B. Un langage de programmation blockchain.
    * C. Un portefeuille électronique.
    * D. Un nouveau protocole de communication.

**Comment by Abde-exe** [comment]
Version code solidity :

[questions.txt](https://github.com/MaximeCours/rendu-web3-team1/files/13875729/questions.txt)

**Comment by Maxime-p** [comment]
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract QuizContract {
    struct Question {
        string statement;
        string[4] answers;
    }

    Question[10] public questions;

    constructor() {
        questions[0] = Question("Qu'est-ce que le Web 3.0 ?", ["Une version améliorée du navigateur Internet Explorer.", "Un réseau social populaire.", "Un nouveau protocole de communication pour le courrier électronique.", "Une évolution du Web vers un Internet décentralisé."]);
        questions[1] = Question("Quel est le principal objectif du Web 3.0 ?", ["Améliorer la vitesse de connexion Internet.", "Décentraliser les applications et les données.", "Augmenter la résolution des écrans d'ordinateur.", "Réduire la taille des fichiers multimédias."]);
        questions[2] = Question("Qu'est-ce qu'un smart contract ?", ["Un contrat intelligent entre deux entreprises.", "Un document juridique traditionnel.", "Un accord verbal entre parties contractantes.", "Un programme informatique auto-exécutable sur une blockchain."]);
        questions[3] = Question("Quelle blockchain est principalement associée à l'utilisation de smart contracts ?", ["Bitcoin.", "Ethereum.", "Ripple.", "Litecoin."]);
        questions[4] = Question("Comment fonctionne la décentralisation dans le contexte du Web 3.0 ?", ["Les données sont réparties sur plusieurs nœuds sans contrôle central.", "Toutes les données sont stockées sur un seul serveur.", "Un seul utilisateur a le contrôle total du réseau.", "Les données sont stockées uniquement sur des serveurs gouvernementaux."]);
        questions[5] = Question("Quelle est la caractéristique principale d'un smart contract par rapport à un contrat traditionnel ?", ["Il nécessite une signature manuscrite.", "Il est exécuté automatiquement sans intermédiaire.", "Il peut être annulé à tout moment.", "Il est stocké sur une base de données centralisée."]);
        questions[6] = Question("Quel langage de programmation est souvent utilisé pour écrire des smart contracts ?", ["Python.", "JavaScript.", "Solidity.", "Ruby."]);
        questions[7] = Question("Qu'est-ce que Hardhat dans le contexte du développement de smart contracts ?", ["Un environnement de développement pour Ethereum.", "Une casquette résistante.", "Un protocole de sécurité sur Internet.", "Un langage de programmation."]);
        questions[8] = Question("Quel est le rôle principal de MetaMask dans l'écosystème Ethereum ?", ["Gérer les mots de passe des utilisateurs.", "Faciliter l'échange de cryptomonnaies.", "Fournir une interface utilisateur pour les smart contracts.", "Stocker des fichiers sur la blockchain."]);
        questions[9] = Question("Qu'est-ce que Sepolia dans le contexte du Web 3.0 ?", ["Un réseau social décentralisé.", "Un langage de programmation blockchain.", "Un portefeuille électronique.", "Un nouveau protocole de communication."]);
    }
}

```
